[build]
builder = "Nixpacks"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmds = ["python telegram_bot.py"]
