# Tell Railway to use Dockerfile instead of Nixpacks
[build]
builder = "Docker"

# Define the service
[service]
name = "meal-planner-bot"
start = "python telegram_bot.py"

# Optional: environment variables (you can also set these in Railway UI)
[env]
TELEGRAM_TOKEN = ""
MEALS_CSV = "meals.csv"
DATA_JSON = "data.json"
