# Use the official lightweight Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy all files from current directory to /app inside the container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variable for Telegram token (optional, you can set it in Railway)
ENV TELEGRAM_TOKEN=${TELEGRAM_TOKEN}

# Run the bot
CMD ["python", "telegram_bot.py"]
